version: "3.7"

services:
  backend:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: beers
      MONGO_INITDB_ROOT_PASSWORD: beers