version: '3.7'

services:
  backend:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    #environment:
    #MONGO_INITDB_DATABASE: beers
    #MONGO_INITDB_ROOT_USERNAME: beers
    #MONGO_INITDB_ROOT_PASSWORD: beers
